# Site settings
email: qCring@gmail.com
baseurl: /QuickVtk
url: ""

collections_dir: content
collections:
  api:
    output: true
  guide:
    output: true
  roadmap:
    output: true
  docs:
    output: true
  research:
    output: true
  examples:
    output: true

# .css/.js files will be cached by the browser so make sure to increment the
# file suffix or use a unique version-sepcific filename in order to bypass
# previously cached resources! something like checksum based naming would be
# nice but since custom jekyll plugins are not supported by GH pages yet,
# this has to be done manually...
style_path: "/assets/css/rev-1.css"
js_path: "/assets/js/rev-1.js"

# Build settings
safe: true
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
excerpt_separator: "\n\n\n"

plugins:
  - jekyll-feed

# Project settings
project_name: QuickVtk
project_description: description
project_version: 0.5.6
project_github_url: "https://github.com/qCring/QuickVtk/"
project_src_url: "https://github.com/qCring/QuickVtk/tree/master/src/"
vtk_url: "https://vtk.org/doc/nightly/html/"
