# Site settings
email: qCring@gmail.com
baseurl: /QuickVtk
url: ""

collections_dir: content
collections:
  api:
    output: true

style_path: "/assets/css/rev-1.css"

# Build settings
safe: true
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

# Project settings
project_name: QuickVtk
project_description: description
project_version: 0.5.6
project_github_url: "https://github.com/qCring/QuickVtk/"
project_src_url: "https://github.com/qCring/QuickVtk/tree/master/src/"
vtk_url: "https://vtk.org/doc/nightly/html/"
